### ISSUE TITLE
Feedback Request: Number Guessing Game

### ISSUE THREAD

**Issue by QuincyTjia** [TechGrounds-Cloud8/cloud8-QuincyTjia#46]
**Feedback Request [NGG]**
Permalink to file: https://github.com/TechGrounds-Cloud8/cloud8-QuincyTjia/blob/b422e51c3eb406652f157aae40b3a3dac2ab7c4d/07_Python_01/PRG-09%20Mini%20Project%20Number%20Guessing%20Game.py

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
Your code looks good and works well! There are a few improvements you could make:

- The game doesn't tell me the range of which the number is (0 - 100)
- The game allows me to input numbers outside of that range
- The game crashes when I type in a letter

some tips:
- on line 7, you could just write `while True:` (saves you writing a line of code and in this case, being lazy is good ;)). On line 12, you can then use `break` instead of changing 'game' to False. The break keyword breaks the loop its currently in (which is the While loop initiated on line 7). 
- `continue` on line 19 currently doesn't do anything. The while loop is still true if the script makes it to that point/line, so it will just loop back to line 8/continue anyway :)

**Comment by sasudi90** [comment]
GG Quincy. Got some things which you may consider:

- a boolean does not need to be declared (in this case to 'game'). It's possible to just use while True. 
- what if I type in a random string instead of an integer? You can use a try... except  to catch such errors and shoot a error message out 
- put a scope for the numbers I can goo over 9000
